#!/usr/bin/env bash
set -eo pipefail

BUILDPACK_INSTALL_PATH="/tmp/buildpacks"

download_buildpack() {
    buildpack_url="$1"
    buildpack_name=$(basename $buildpack_url)
    buildpack_commit="$2"

    git clone $buildpack_url $BUILDPACK_INSTALL_PATH/$buildpack_name
    pushd $BUILDPACK_INSTALL_PATH/$buildpack_name 2>&1 >/dev/null
        git checkout --quiet $buildpack_commit
    popd 2>&1 >/dev/null
}

mkdir -p $BUILDPACK_INSTALL_PATH

download_buildpack https://github.com/qtcloudservices/qtc-buildpack-qt.git       0a50d54
download_buildpack https://github.com/qtcloudservices/qtc-buildpack-ruby.git     8f60443
download_buildpack https://github.com/qtcloudservices/qtc-buildpack-nodejs.git   7349622
download_buildpack https://github.com/qtcloudservices/qtc-buildpack-java.git     ff892da
download_buildpack https://github.com/qtcloudservices/qtc-buildpack-python.git   c5d00b3
download_buildpack https://github.com/qtcloudservices/qtc-buildpack-php.git      d4055c2

chown -R slugbuilder:slugbuilder "$BUILDPACK_INSTALL_PATH"
